### ISSUE TITLE
Support partial configs in JSON schema

### ISSUE THREAD

**Issue by roedoejet** [EveryVoiceTTS/EveryVoice#102]
```yaml
model:
  decoder: {conformer: true, conv_filter_size: 1024, conv_kernel_size: 9, depthwise: true,
    dropout: 0.2, feedforward_dim: 1024, heads: 2, hidden_dim: 256, layers: 4}
  encoder: {conformer: true, conv_filter_size: 1024, conv_kernel_size: 9, depthwise: true,
    dropout: 0.2, feedforward_dim: 1024, heads: 2, hidden_dim: 256, layers: 4}
  learn_alignment: true
  max_length: 1000
  ...
preprocessing: /gpfs/fs2c/nrc/dt/sgile/data/SinhalaTTS/sep19-2023-test/config/preprocessing.yaml
```

The preprocessing value is a path to a PreprocessingConfig, and this is currently registered as an error by intellisense. We need to permit paths for certain fields that are allowed to have partials.
