### ISSUE TITLE
Specifying multispeaker/multilanguage during `new-project` doesn't enable multispeaker/multilanguage in configuration

### ISSUE THREAD

**Issue by SamuelLarkin** [EveryVoiceTTS/EveryVoice#203]
When creating a new project through `everyvoice new-project` and specifying that the data has a speaker column, which would imply a multispeaker dataset, it doesn't set it so in the configuration file.

`config/everyvoice-text-to-spec.yaml`
```yaml
model:
  multilingual: false
  multispeaker: false
```
