### ISSUE TITLE
Missing file during training of vocoder

### ISSUE THREAD

**Issue by SamuelLarkin** [EveryVoiceTTS/EveryVoice#25]
Note that the config files are the one automatically generated.

Looks more like a filename that is generated differently by two piece of code.

`python -m everyvoice hifigan train -p corpus/config/vocoder.yaml`

```
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/fs2c/nrc/dt/sam037/uat/EveryVoice/uat/corpus/preprocessed/training_filelist.psv'
```

```yaml
cat corpus/config/vocoder.yaml
model:
  activation_function: everyvoice.utils.original_hifigan_leaky_relu
  depthwise_separable_convolutions: {generator: false}
  istft_layer: true
  mpd_layers: [2, 3, 5, 7, 11]
  msd_layers: 3
  resblock: '1'
  resblock_dilation_sizes:
  - [1, 3, 5]
  - [1, 3, 5]
  - [1, 3, 5]
  resblock_kernel_sizes: [3, 7, 11]
  upsample_initial_channel: 512
  upsample_kernel_sizes: [16, 16]
  upsample_rates: [8, 8]
preprocessing: /gpfs/fs2c/nrc/dt/sam037/uat/EveryVoice/uat/corpus/config/preprocessing.yaml
training:
  batch_size: 16
  ckpt_epochs: 1
  ckpt_steps: null
  filelist_loader: everyvoice.utils.generic_dict_loader
  finetune: false
  finetune_checkpoint: null
  freeze_layers: {all_layers: false, generator: false, mpd: false, msd: false}
  gan_type: original
  generator_warmup_steps: 0
  logger: {name: VocoderExperiment, save_dir: /gpfs/fs2c/nrc/dt/sam037/uat/EveryVoice/uat/corpus/logs,
    sub_dir: everyvoice.utils.get_current_time, version: base}
  max_epochs: 1000
  max_steps: 100000
  optimizer:
    betas: [0.9, 0.98]
    eps: 1.0e-08
    learning_rate: 0.0001
    name: adamw
    weight_decay: 0.01
  save_top_k_ckpts: 5
  train_data_workers: 4
  training_filelist: /gpfs/fs2c/nrc/dt/sam037/uat/EveryVoice/uat/corpus/preprocessed/training_filelist.psv
  use_weighted_sampler: false
  val_data_workers: 0
  validation_filelist: /gpfs/fs2c/nrc/dt/sam037/uat/EveryVoice/uat/corpus/preprocessed/validation_filelist.psv
  wgan_clip_value: 0.01
```

```bash
lsd /gpfs/fs2c/nrc/dt/sam037/uat/EveryVoice/uat/corpus/preprocessed/
drwxrwx--- sam037 nrc_ict 4.0 KB Wed May 24 15:37:30 2023  attn
drwxrwx--- sam037 nrc_ict 4.0 KB Wed May 24 15:37:29 2023  audio
drwxrwx--- sam037 nrc_ict 4.0 KB Wed May 24 15:37:31 2023  energy
drwxrwx--- sam037 nrc_ict 4.0 KB Wed May 24 15:37:31 2023  pitch
.rw-rw---- sam037 nrc_ict 1.1 KB Wed May 24 15:37:29 2023  processed_filelist.psv
drwxrwx--- sam037 nrc_ict 4.0 KB Wed May 24 15:37:30 2023  spec
.rw-rw---- sam037 nrc_ict 401 B  Wed May 24 15:37:31 2023  stats.json
.rw-rw---- sam037 nrc_ict 234 B  Wed May 24 15:37:29 2023  summary.txt
drwxrwx--- sam037 nrc_ict 4.0 KB Wed May 24 15:37:29 2023  text
.rw-rw---- sam037 nrc_ict 1.0 KB Wed May 24 15:37:29 2023  training-processed_filelist.psv
.rw-rw---- sam037 nrc_ict 128 B  Wed May 24 15:37:29 2023  validation-processed_filelist.psv
```
